### PR TITLE
Adapt to new Hugo theme site

### PR DESCRIPTION
**Pull request by bep**
Add screen shots and metadata and a minor template tweak.

### CODE REVIEW

**Comment by bep** [comment]
Bump.

Note, we need this before we can go live with the new Hugo Theme Site.

**Comment by bep** [comment]
bump

**Comment by crakjie** [comment]
Bump?

Envoyé de mon iPhone

**Comment by bep** [comment]
Bump, as in, please merge.

**Comment by crakjie** [comment]
I was thinking I had aleady merged it , sorry

**Pull request merged**
