### PR TITLE
Update head.html

### PR DESCRIPTION
**Pull request by alanef**
Added capability to add 'local' css files  using a parameter as suggest here https://discuss.gohugo.io/t/how-to-override-css-classes-with-hugo/3033/3

### CODE REVIEW

**Comment by crakjie** [comment]
Do you think this need an exemple in exempleSite ?

**Comment by alanef** [comment]
In the README.md yes.

Example site maybe

I did this because I wanted a background-color to  the contact area rather than image

static/css/local.css

.contact {
  background-color: #b6b6b6;
}

If you want me to update example & README let me know and I will and create a pull

**Comment by alanef** [comment]
for config.toml

[params]
  custom_css = ["css/local.css"]

**Comment by crakjie** [comment]
I think it's alway good to have things in docs.
Maybe a line in the README.

But you can just add a commit to this PR, I think it's cleaner, don't you ?

**Comment by alanef** [comment]
OK  I have added to README & the example site

**Comment by alanef** [comment]
Sorry about the list of commits as did them directly in github - probably bad form

**Comment by crakjie** [comment]
LGFM

**Pull request merged**
